### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [8wondrs/8wondrs.github.io#3]
http://joxi.ru/L21b6x0F6GyxEA
1) сделать фон на весь браузер.
2) поправь меню

**Comment by 8wondrs** [comment]
исправил

**Comment by AndriiLitvin** [comment]
http://joxi.ru/brR6zPluQyx5Dr
-
1)сделать на весь браузер
2)кнопку сверстать.
3)фокус смотреть на макете
4)убрать .wrapper высоту и body {background-size: cover;}

**Comment by 8wondrs** [comment]
поправил
